[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "production", "scanpoint", "customer"]}

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
